default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: jdilib_development

test:
  <<: *default
  database: jdilib_test

production:
  <<: *default
  database: jdilib_production
  username: jdilib
  password: <%= ENV['JDILIB_DATABASE_PASSWORD'] %>
